<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComposeValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\ComposeValidator' shared autowired service.
     *
     * @return \App\Validator\ComposeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/ComposeValidator.php';

        return $container->privates['App\\Validator\\ComposeValidator'] = new \App\Validator\ComposeValidator();
    }
}
