<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitTokenValidValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\InitTokenValidValidator' shared autowired service.
     *
     * @return \App\Validator\InitTokenValidValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/InitTokenValidValidator.php';

        return $container->privates['App\\Validator\\InitTokenValidValidator'] = new \App\Validator\InitTokenValidValidator();
    }
}
