<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIterableVoterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.App\Security\Voter\IterableVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/AbstractVoter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/IterableVoter.php';

        $a = ($container->privates['debug.security.access.decision_manager'] ?? self::getDebug_Security_Access_DecisionManagerService($container));

        if (isset($container->privates['.debug.security.voter.App\\Security\\Voter\\IterableVoter'])) {
            return $container->privates['.debug.security.voter.App\\Security\\Voter\\IterableVoter'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.App\\Security\\Voter\\IterableVoter'])) {
            return $container->privates['.debug.security.voter.App\\Security\\Voter\\IterableVoter'];
        }

        return $container->privates['.debug.security.voter.App\\Security\\Voter\\IterableVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \App\Security\Voter\IterableVoter($a), $b);
    }
}
