<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_CookieProvider_JwtHpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'lexik_jwt_authentication.cookie_provider.jwt_hp' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Security/Http/Cookie/JWTCookieProvider.php';

        return $container->privates['lexik_jwt_authentication.cookie_provider.jwt_hp'] = new \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider('jwt_hp', 1800, 'strict', '/', NULL, true, false, ['header', 'payload']);
    }
}
