<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_SetRecipientsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.set_recipients' shared autowired service.
     *
     * @return \Symfony\Component\Mailer\EventListener\EnvelopeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/EventListener/EnvelopeListener.php';

        return $container->privates['mailer.set_recipients'] = new \Symfony\Component\Mailer\EventListener\EnvelopeListener(NULL, (($container->getParameter("mailer_recipient")) ? ([0 => $container->getParameter("mailer_recipient")]) : (null)));
    }
}
