<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_CookieClearing_ApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.cookie_clearing.api' shared service.
     *
     * @return \Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EventListener/CookieClearingLogoutListener.php';

        return $container->privates['security.logout.listener.cookie_clearing.api'] = new \Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener(['jwt_hp' => ['path' => NULL, 'domain' => NULL, 'secure' => false, 'samesite' => NULL], 'jwt_s' => ['path' => NULL, 'domain' => NULL, 'secure' => false, 'samesite' => NULL]]);
    }
}
