<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserInitPasswordRequestProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\UserInitPasswordRequestProcessor' shared autowired service.
     *
     * @return \App\State\UserInitPasswordRequestProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/UserInitPasswordRequestProcessor.php';

        $a = ($container->privates['App\\Service\\UserService'] ?? $container->load('getUserServiceService'));

        if (isset($container->privates['App\\State\\UserInitPasswordRequestProcessor'])) {
            return $container->privates['App\\State\\UserInitPasswordRequestProcessor'];
        }

        return $container->privates['App\\State\\UserInitPasswordRequestProcessor'] = new \App\State\UserInitPasswordRequestProcessor($a);
    }
}
