<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserUpdatePasswordRequestProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\UserUpdatePasswordRequestProcessor' shared autowired service.
     *
     * @return \App\State\UserUpdatePasswordRequestProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/UserUpdatePasswordRequestProcessor.php';

        return $container->privates['App\\State\\UserUpdatePasswordRequestProcessor'] = new \App\State\UserUpdatePasswordRequestProcessor(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
