services:
    angular:
        # image: ${GITLAB_REGISTRY}/a5sys/a5sys-app-starter-kit/frontend-angular/dev:latest
        build:
            context: ./docker/image/node/dev/
            dockerfile: ./Dockerfile
        tty: true
        volumes:
            - .:/app/
        ports:
            - "4200:4200"
            - "4201:4201"
        entrypoint: ./docker/entrypoint/angular.sh
