services:
    nginx:
        image: nginx:alpine
        tty: true
        depends_on:
            - php
        volumes:
            - ./public:/srv/nginx/public:ro,cached
            - ./docker/image/nginx/conf.d/php.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"

    php:
        build:
            context: ./docker/image/php/base/
            dockerfile: ./Dockerfile
        tty: true
        depends_on:
            - postgres
        volumes:
            - .:/srv/php:rw,cached
            - ./var:/srv/php/var:rw
        entrypoint: ./docker/entrypoint/php.sh
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    postgres:
        image: postgres:16
        tty: true
        env_file:
            - ./.env
        ports:
            - "5432:5432"

    mailcatcher:
        image: jeanberu/mailcatcher:latest
        tty: true
        ports:
            - "1025:1025"
            - "1080:1080"
        # command:
        #     - "--http-ip=0.0.0.0"
        #     - "--smtp-ip=0.0.0.0"
