<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container81AQpgh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container81AQpgh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container81AQpgh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container81AQpgh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container81AQpgh\App_KernelDevDebugContainer([
    'container.build_hash' => '81AQpgh',
    'container.build_id' => 'e6edf390',
    'container.build_time' => 1715079942,
], __DIR__.\DIRECTORY_SEPARATOR.'Container81AQpgh');
